<?xml version="1.0" encoding="ISO-8859-1"?>
<definitions xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="urn:gestreportwsdl" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="urn:gestreportwsdl">
<types>
<xsd:schema targetNamespace="urn:gestreportwsdl">
<xsd:import namespace="http://schemas.xmlsoap.org/soap/encoding/"/>
<xsd:import namespace="http://schemas.xmlsoap.org/wsdl/"/>
</xsd:schema>
</types>
<message name="gestionreportingRequest">
<part name="token" type="xsd:string"/>
</message>
<message name="gestionreportingResponse">
<part name="return" type="xsd:string"/>
</message>
<portType name="gestreportPortType">
<operation name="gestionreporting">
<documentation>Method gestreport gestionreporting</documentation>
<input message="tns:gestionreportingRequest"/>
<output message="tns:gestionreportingResponse"/>
</operation>
</portType>
<binding name="gestreportBinding" type="tns:gestreportPortType">
<soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
<operation name="gestionreporting">
<soap:operation soapAction="urn:gestreportwsdl#gestionreporting" style="rpc"/>
<input>
<soap:body use="encoded" namespace="urn:gestreportwsdl" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
</input>
<output>
<soap:body use="encoded" namespace="urn:gestreportwsdl" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
</output>
</operation>
</binding>
<service name="gestreport">
<port name="gestreportPort" binding="tns:gestreportBinding">
<soap:address location="http://localhost/EsquisseBackEnd/web/app_dev.php/invest/gestionreporting"/>
</port>
</service>
</definitions>