ws_client:
    resource: "@WSClientBundle/Resources/config/routing.yml"
    prefix:   /client

ws_server:
    resource: "@WSServerBundle/Resources/config/routing.yml"
    prefix:   /invest

ws:
    resource: "@WSBundle/Resources/config/routing.yml"
    prefix:   /
