<?php

namespace WSServerBundle\Repository;

/**
 * AuthorizedsessionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticlesRepository extends \Doctrine\ORM\EntityRepository
{
	// public function getArticles()
	// {
	//     return $this->getEntityManager()
 //           ->createQuery(
 //           'SELECT a FROM WSServerBundle:Articles a'
 //           )
 //           ->getResult();
	// }
}
