<?php

namespace WSServerBundle\Repository;

/**
 * CommissionnementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommissionnementsRepository extends \Doctrine\ORM\EntityRepository
{
}
