<?php

namespace WSServerBundle\Repository;

/**
 * fraistransfertsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class fraistransfertsRepository extends \Doctrine\ORM\EntityRepository
{
}
