<?php

namespace WSServerBundle\Repository;

/**
 * PrerogativeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrerogativeRepository extends \Doctrine\ORM\EntityRepository
{
}
