<?php

namespace WSServerBundle\Repository;

/**
 * RetraitfondRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RetraitfondRepository extends \Doctrine\ORM\EntityRepository
{
}
