<?php

namespace WSServerBundle\Repository;

/**
 * AuthorizedsessionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TigocashRepository extends \Doctrine\ORM\EntityRepository
{
}
