<?php

namespace WSServerBundle\Repository;

/**
 * AuthorizedsessionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TntRepository extends \Doctrine\ORM\EntityRepository
{

/*	public function findCardOrChip($numero)
	{
	  $query = $this->_em->createQuery('SELECT t.infosoperation FROM Tnt  WHERE t.infosoperation like '%:numero%' ');
	  $query->setParameter('numero', $numero);
	  
	  return $query->getSingleResult();
	} */
}
