<?php


namespace WSServerBundle\Repository;


/**
 * TntRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class TntRepository extends \Doctrine\ORM\EntityRepository
{

	public function findByinfosoperation($numero)
	{
		$queryBuilder = $this->createQueryBuilder('t') ;
		$query = $queryBuilder->getQuery() ;
		$results = $query->getResult() ;
		return $results ;
	} 
}

