services:
#    ws.example:
#        class: WSBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    hello_service:
        class: WSBundle\Services\HelloService
        #arguments: ['@mailer']
